export const people = [
    { id: 'LolaDunam', tag: 'span', classe: 'modern', active: false },
    { id: 'LeeMarley', tag: 'span', classe: 'baroque', active: false },
    { id: 'JeanDujardin', tag: 'a', classe: 'classical', active: true },
    { id: 'MarloStanfield', tag: 'span', classe: 'modern', active: false },
    { id: 'GeorgesDrumond', tag: 'span', classe: 'baroque', active: true },
    { id: 'JuliaWhite', tag: 'span', classe: 'modern', active: true },
    { id: 'BarneyLeberre', tag: 'span', classe: 'modern', active: true },
    { id: 'DavidCarretta', tag: 'a', classe: 'classical', active: false },
    { id: 'AugustoCesar', tag: 'span', classe: 'modern', active: true },
    { id: 'DavidGuetta', tag: 'a', classe: 'modern', active: false },
    { id: 'MarlonBrando', tag: 'a', classe: 'classical', active: false },
    { id: 'BonannoPisano', tag: 'a', classe: 'classical', active: true },
    { id: 'AvonBarksdale', tag: 'span', classe: 'baroque', active: true },
    { id: 'BarackObama', tag: 'span', classe: 'baroque', active: false },
    { id: 'MarcDupont', tag: 'span', classe: 'modern', active: false },
    { id: 'BillieElliott', tag: 'a', classe: 'baroque', active: true },
    { id: 'MariaCallas', tag: 'a', classe: 'baroque', active: false },
    { id: 'SteveJobbs', tag: 'a', classe: 'classical', active: false },
    { id: 'JoeLee', tag: 'span', classe: 'baroque', active: false },
    { id: 'AnthonyGrant', tag: 'span', classe: 'baroque', active: false },
    { id: 'ShakimaGreggs', tag: 'a', classe: 'modern', active: true },
    { id: 'RoyDeere', tag: 'span', classe: 'baroque', active: true },
    { id: 'BobTurner', tag: 'a', classe: 'classical', active: true },
    { id: 'AngeloCapri', tag: 'span', classe: 'modern', active: false },
    { id: 'SamMcDonald', tag: 'span', classe: 'baroque', active: true },
    { id: 'FannyLelouche', tag: 'span', classe: 'baroque', active: true },
    { id: 'ClarkLoister', tag: 'a', classe: 'classical', active: false },
    { id: 'FinanObrien', tag: 'span', classe: 'modern', active: false },
    { id: 'ClariceSterling', tag: 'a', classe: 'modern', active: true },
    { id: 'JayHernan', tag: 'span', classe: 'baroque', active: true },
    { id: 'HelenMirren', tag: 'a', classe: 'classical', active: false },
    { id: 'SarahForestier', tag: 'a', classe: 'modern', active: false },
    { id: 'JacquesChirac', tag: 'a', classe: 'classical', active: true },
    { id: 'MartinWealer', tag: 'a', classe: 'baroque', active: true },
    { id: 'JodieFoster', tag: 'span', classe: 'baroque', active: true },
    { id: 'JeanJacques', tag: 'span', classe: 'modern', active: false },
    { id: 'MollyHeart', tag: 'a', classe: 'baroque', active: false },
    { id: 'FabioSalso', tag: 'a', classe: 'classical', active: true },
    { id: 'CarlosSanchez', tag: 'span', classe: 'baroque', active: true },
    { id: 'RussellBell', tag: 'a', classe: 'classical', active: false },
    { id: 'JackDoe', tag: 'span', classe: 'baroque', active: true },
    { id: 'EricCarver', tag: 'a', classe: 'classical', active: false },
    { id: 'LouisDeschamps', tag: 'span', classe: 'baroque', active: true },
    { id: 'HoracioCane', tag: 'a', classe: 'baroque', active: true },
    { id: 'HenryBright', tag: 'a', classe: 'baroque', active: true },
  ]

  export const styles = [
    'one',
    'two',
    'three',
    'four',
    'five',
    'six',
    'seven',
    'eight',
    'nine',
    'ten',
    'eleven',
    'twelve',
    'thirteen',
    'fourteen',
    'fifteen',
  ]


  export const colors = [
    'indianred',
    'lightcoral',
    'salmon',
    'darksalmon',
    'lightsalmon',
    'crimson',
    'red',
    'firebrick',
    'darkred',
    'pink',
    'lightpink',
    'hotpink',
    'deeppink',
    'mediumvioletred',
    'palevioletred',
    'orange',
    'coral',
    'tomato',
    'orangered',
    'darkorange',
    'yellow',
    'gold',
    'lightyellow',
    'lemonchiffon',
    'lightgoldenrodyellow',
    'papayawhip',
    'moccasin',
    'peachpuff',
    'palegoldenrod',
    'khaki',
    'darkkhaki',
    'lavender',
    'thistle',
    'plum',
    'violet',
    'orchid',
    'fuchsia',
    'magenta',
    'mediumorchid',
    'mediumpurple',
    'rebeccapurple',
    'blueviolet',
    'darkviolet',
    'darkorchid',
    'darkmagenta',
    'purple',
    'indigo',
    'slateblue',
    'darkslateblue',
    'green',
    'greenyellow',
    'chartreuse',
    'lawngreen',
    'lime',
    'limegreen',
    'palegreen',
    'lightgreen',
    'mediumspringgreen',
    'springgreen',
    'mediumseagreen',
    'seagreen',
    'forestgreen',
    'darkgreen',
    'yellowgreen',
    'olivedrab',
    'olive',
    'darkolivegreen',
    'mediumaquamarine',
    'darkseagreen',
    'lightseagreen',
    'darkcyan',
    'teal',
    'aqua',
    'cyan',
    'lightcyan',
    'paleturquoise',
    'aquamarine',
    'turquoise',
    'mediumturquoise',
    'darkturquoise',
    'cadetblue',
    'steelblue',
    'lightsteelblue',
    'powderblue',
    'lightblue',
    'skyblue',
    'lightskyblue',
    'deepskyblue',
    'dodgerblue',
    'cornflowerblue',
    'mediumslateblue',
    'royalblue',
    'blue',
    'mediumblue',
    'darkblue',
    'navy',
    'midnightblue',
    'brown',
    'cornsilk',
    'blanchedalmond',
    'bisque',
    'navajowhite',
    'wheat',
    'burlywood',
    'tan',
    'rosybrown',
    'sandybrown',
    'goldenrod',
    'darkgoldenrod',
    'peru',
    'chocolate',
    'saddlebrown',
    'sienna',
    'maroon',
    'white',
    'snow',
    'honeydew',
    'mintcream',
    'azure',
    'aliceblue',
    'ghostwhite',
    'whitesmoke',
    'seashell',
    'beige',
    'oldlace',
    'floralwhite',
    'ivory',
    'antiquewhite',
    'linen',
    'lavenderblush',
    'mistyrose',
    'gainsboro',
    'lightgray',
    'silver',
    'darkgray',
    'gray',
    'dimgray',
    'lightslategray',
    'slategray',
    'darkslategray',
    'black',
  ]


  export const gossips = [
    `Oasis star Noel Gallagher used to gorge on Greggs pastries and donuts every day`,
    `Lea Michele's lookalike Monica Moskatow says Glee star called her ugly`,
    `WE PAY FOR JUICY INFO!`,
    `Trainer to Hollywood's biggest stars reveals how to get an A-list body`,
    `Ed Sheeran comes out of music retirement to write brand new song`,
    `Kylie Jenner & Travis Scott€™s breakup timeline`,
    `Quiet on the set: temper tantrums stars hope you forget`,
    `The style & grace of ChloÃ« Grace Moretz: her top 20 red carpet looks`,
    `Paulina Porizkova feels betrayed after being cut out of husband Ric Ocasek's will`,
    `From too hot to not: Paris Hilton and Chris Zylka's relationship history`,
    `No bite in the big apple? Celine Dion looks scary skinny in New York`,
    `Jennifer Aniston and Brad Pitt relationship timeline`,
    `They shouldn€™t have said that: 10 celebrity rants heard around the world`,
    `The most intense celebrity fights on set`,
    `The 18 most bitter real housewives feuds`,
    `Tristan Thompson's remarkable transformation from skinny teen to hulking NBA ace`,
    `Kim Kardashian 'considers leaving home' with Kanye West to 'save marriage'`,
  ]


  export const places = [
    {
      name: 'Cordoba, Spain',
      color: 'deeppink',
      coordinates: `37°53'17.43"N 4°46'45.78"W`,
    },
    {
      name: 'Yuanyang County, China',
      color: 'cyan',
      coordinates: `23°09'32.30"N 102°44'41.46"E`,
    },
    {
      name: 'Namib Desert, Namibia',
      color: 'lime',
      coordinates: `24°45'4.19"S 15°16'21.00"E`,
    },
    {
      name: 'Newark, New Jersey, USA',
      color: 'yellow',
      coordinates: `40°44'8.37"N 74°10'20.52"W`,
    },
    {
      name: 'Nishinoshima Island, Japan',
      color: 'lightcoral',
      coordinates: `27°14'50.84"N 140°52'46.04"E`,
    },
    {
      name: 'Lisse, The Netherlands',
      color: 'cornflowerblue',
      coordinates: `52°15'28.55"N 4°33'26.94"E`,
    },
    {
      name: 'Shadegan Lagoon, Iran',
      color: 'firebrick',
      coordinates: `30°39'16.55"N 48°39'14.14"E`,
    },
    {
      name: 'Qinhuangdao, China',
      color: 'seashell',
      coordinates: `39°56'7.3"N 119°36'1.88"E`,
    },
    {
      name: 'Marrakesh, Morocco',
      color: 'orange',
      coordinates: `31°37'46.1"N 7°58'51.9"W`,
    },
    {
      name: 'Los Caracoles Pass, Chile',
      color: 'violet',
      coordinates: `32°49'51.6"S 70°05'22.9"W`,
    },
    {
      name: 'Tucson, Arizona, USA',
      color: 'springgreen',
      coordinates: `32°13'21.38"N 110°58'28.96"W`,
    },
    {
      name: 'Arlit, Niger',
      color: 'blue',
      coordinates: `18°44'20.41"N 7°23'22.12"E`,
    },
    {
      name: 'Black Rock Desert, Nevada, USA',
      color: 'crimson',
      coordinates: `40°54'35.0"N 119°03'26.5"W`,
    },
    {
      name: 'Mount Fuji, Japan',
      color: 'darkviolet',
      coordinates: `35°21'37.0"N 138°43'38.1"E`,
    },
    {
      name: 'Moab, Utah, USA',
      color: 'gold',
      coordinates: `38°34'23.94"N 109°32'59.42"W`,
    },
    {
      name: 'Rio de Janeiro, Brasil',
      color: 'hotpink',
      coordinates: `22°59'13.4"S 43°12'15.9"W`,
    },
    {
      name: 'Killeen, Texas, USA',
      color: 'greenyellow',
      coordinates: `31°07'1.63"N 97°43'40.07"W`,
    },
    {
      name: 'Skafta River, Iceland',
      color: 'mistyrose',
      coordinates: `63°39'47.7"N 17°47'57.9"W`,
    },
    {
      name: 'Almeria, Spain',
      color: 'mediumturquoise',
      coordinates: `36°50'08.7"N 2°27'44.8"W`,
    },
    {
      name: 'Atlanta, Georgia, USA',
      color: 'white',
      coordinates: `33°45'39.0"N 84°23'50.1"W`,
    },
    {
      name: 'Georgetown, California, USA',
      color: 'sandybrown',
      coordinates: `38°54'22.4"N 120°50'23.9"W`,
    },
  ]